---
- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: install deps
  become: yes
  apt:
    name: ["nodejs", "npm"]
    update_cache: yes

- name: install 
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: create directory
  file:
    path: ~/web
    state: directory

- name: copy index test page
  template:
    src: "files/index.js"
    dest: "~/web/index.js"

- name: start node
  shell: |
    pm2 start ~/web/index.js -f


